config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :trains

  resources :products

  get 'site/index'

  get 'site/about'

  get 'site/contact'

  get 'site/blog'

  get 'site/show'

  get 'site/train'

   get 'site/showtrain'

   root 'site#index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new #guest user
    if user.role? :admin
        can :manage, :all
    else
        can :read, :all
  end
end 
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
 

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/product.rb
class Product < ActiveRecord::Base
	mount_uploader :image, ImageUploader
	extend FriendlyId
	friendly_id :name, use: [:slugged, :finders]
end

app/models/train.rb
class Train < ActiveRecord::Base
	mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
    if request.path != product_path(@product)
      redirect_to @product, status: :moved_permanently
    end
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :image, :video, :description, :slug, :logo)
    end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  def index
  	@products = Product.last(2)
    @trains = Train.last(3)
  end

  def about
  end

  def train
  	@trains = Train.all
    @tran = Train.last(1)
  end

  def show
    @product = Product.friendly.find(params[:product_id])
    # if request.path != product_path(@product)
    #   redirect_to @product, status: :moved_permanently
    # end
  end

  def showtrain
    @train = Train.find(params[:train_id])
  end

  def contact
  end

  def blog
  	@products = Product.all
  	@prolast = Product.last(1)
  end
end

app/controllers/trains_controller.rb
class TrainsController < ApplicationController
  before_action :set_train, only: [:show, :edit, :update, :destroy]

  # GET /trains
  # GET /trains.json
  def index
    @trains = Train.all
  end

  # GET /trains/1
  # GET /trains/1.json
  def show
  end

  # GET /trains/new
  def new
    @train = Train.new
  end

  # GET /trains/1/edit
  def edit
  end

  # POST /trains
  # POST /trains.json
  def create
    @train = Train.new(train_params)

    respond_to do |format|
      if @train.save
        format.html { redirect_to @train, notice: 'Train was successfully created.' }
        format.json { render :show, status: :created, location: @train }
      else
        format.html { render :new }
        format.json { render json: @train.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trains/1
  # PATCH/PUT /trains/1.json
  def update
    respond_to do |format|
      if @train.update(train_params)
        format.html { redirect_to @train, notice: 'Train was successfully updated.' }
        format.json { render :show, status: :ok, location: @train }
      else
        format.html { render :edit }
        format.json { render json: @train.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trains/1
  # DELETE /trains/1.json
  def destroy
    @train.destroy
    respond_to do |format|
      format.html { redirect_to trains_url, notice: 'Train was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_train
      @train = Train.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def train_params
      params.require(:train).permit(:name, :image, :video, :description, :logo)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/helpers/trains_helper.rb
module TrainsHelper
end

app/views/layouts/_header.html.erb
  <nav class="top-bar" data-topbar>
    <ul class="title-area">
      <li class="name">
        <h1><%= link_to "Anakot",root_path %></h1>
      </li>
      <li class="toggle-topbar menu-icon"><a href="#"></a></li>
    </ul>

  <section class="top-bar-section">
    <!-- Right Nav Section -->
	 <ul class="right">
      <li><%= link_to "Login", new_user_session_path %></li>
    </ul>

    <!-- Left Nav Section -->
    <ul class="left">
      <li><%= link_to "Blog", site_blog_path %></li>
      <li><%= link_to "Training", site_train_path %></li>
      <li><%= link_to "Forum" %></li>
      <li><%= link_to "Contact", site_contact_path %></li>
    </ul>
  </section>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "foundation-rails" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <%= yield %>
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.file_field :image %>
  </div>
  <div class="field">
    <%= f.label :video %>
    <%= f.text_field :video %>
  </div>
  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<h1>Listing products</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Image</th>
      <th>Video</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= product.image %></td>
        <td><%= product.video %></td>
        <td><%= product.description %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<div class="content">
<h1>New product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>
</div>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Image:</strong>
  <%= @product.image %>
</p>

<p>
  <strong>Video:</strong>
  <%= @product.video %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>

app/views/site/_box.html.erb
<div class="content"  style="margin-top:30px; padding:0px;">
<hr style="background:#f1f1f1;margin-bottom:23px;">
<% @products.each do |p| %>
<%= link_to site_show_path(product_id: p) do %>
	<div class="box">
		<div class="pro-img"><%= image_tag p.image,size: "200" %></div>
		<div class="pro-name"><%= p.name %></div>
		<div class="pro-des"><%= truncate(p.description,length: 120) %></div>
		<div class="footer-box">
			<p><i class="fa fa-clock-o"></i></p>
		</div>
	</div>
<% end %>
<% end %>
</div>

app/views/site/_box2.html.erb
<div class="content"  style="margin-top:30px; padding:0px;">
<% @products.each do |p| %>
<%= link_to site_show_path(product_id: p) do %>
	<div class="box2">
		<div class="pro-img"><%= image_tag p.image,size: "200" %></div>
		<div class="pro-name"><%= p.name %></div>
		<div class="pro-des"><%= truncate(p.description,length: 110) %></div>
		<div class="footer-box">
			<p><i class="fa fa-clock-o"></i></p>
		</div>
	</div>
<% end %>
<% end %>
</div>

app/views/site/_train2.html.erb
<div class="content"  style="margin-top:30px; padding:0px;">
<% @trains.each do |train| %>
<%= link_to site_showtrain_path(train_id: train) do %>
	<div class="train2">
		<div class="train-img"><%= image_tag train.image,size: "130" %></div>
		<div class="train-right">
			<div class="train-name"><%= train.name %></div>
			<div class="train-desc"><%= truncate(train.description,length: 110) %></div>
			<!-- <div class="footer-box">
				<p><i class="fa fa-clock-o"></i></p>
			</div>
 -->		</div>
	</div>
	<% end %>
<% end %>
</div>

app/views/site/about.html.erb
<div class="login-form">
	<div class="large-4 large-centered columns">
	<h2><span>Login</span></h2>
	<%= form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
	  <div><%= f.label :email %>
	  <%= f.email_field :email, autofocus: true %></div>

	  <div style="display:flex;"><%= f.label :password %>&nbsp;<%= link_to "Forgot your password?", new_password_path(resource_name),style: "color:#2EADA3;float:right;font-size:0.7em;margin-top:5px;text-transform:underline;" %></div>
	    <%= f.password_field :password, autocomplete: "off" %>

	  <% if devise_mapping.rememberable? -%>
	  	<div class="remember-form">
		    <div><%= f.check_box :remember_me %> <%= f.label :remember_me %></div>
	    </div>
	  <% end -%>
	  <div><%= link_to '<i class="fa fa-facebook fa-1x border" style="font-size:1.3em;"></i> Login with Facebook'.html_safe,root_path, class: "button facebook tiny radius",style: "font-size:0.8em;" %><%= f.submit "Sign in", class: "button vine tiny radius",style: "font-size:0.8em;float:right;" %></div>
	<% end %>
	</div>
</div>

app/views/site/blog.html.erb
<div class="sub-menu">
	<div class="content-sub">
		<h1>Blog videos</h1>
		<p>Learn with my video you will did it....</p>
	</div>
</div>
<div class="mini-menu">
	<div class="content">
		<ul>
			<li><%= link_to "Tutorails",site_blog_path,style: "color:#888" %></li>
		</ul>
	</div>
</div>
<div class="content-box">
<div class="title">
	<span>Last Tutorails</span>
</div>
<div class="last-tutorails">
	<% @prolast.each do |pro| %>
		<div class="large-3 columns" style="padding-left: 0px;"><%= image_tag (pro.image),size: "300" %></div>
		<div class="large-9 columns" style="padding-left:0px;">
			<div class="pro-name"><%= pro.name %></div>	
			<div class="pro-desc"><%= pro.description %></div>
			<%= link_to "View last tutorails", site_show_path(product_id: pro),class: "button tiny vine radius",style: "font-size:1em;margin-top:13px;" %>	
		</div>
	<% end %>
</div>
	<%= render "site/box" %>
</div>

app/views/site/contact.html.erb
<div class="sub-menu">
	<div class="content-sub">
		<h1>Contact</h1>
	</div>
</div>
<div class="mini-menu">
<div class="content">
		<ul>
			<li><%= link_to "Welcome",site_contact_path %></li>
			<li><%= link_to "Contact",site_contact_path,style: "color:#888" %></li>
		</ul>
	</div>
</div>
<div class="content">
<div class="large-12 columns" style="padding:0px;">
	<div class="large-12 olumns" style="padding:0px;">
		<div class="large-8 columns" style="padding:0px;">
			<div class="content-box" style="padding-left:30px;">
				<div class="title"><span>Contact me by email</span></div>
				<p style="margin-top:15px;">If you have problems or a bug in your code does not use this form! Start by searching on <%= link_to "google" %> or on the Forum . If you can not find that topic, create a new topic.</p>
			</div>
		</div>
		<div class="large-4 columns"></div>
	</div>
</div>
</div>

app/views/site/index.html.erb
<div class="sub-menu">
	<div class="content-sub">
		<h1>Anakot</h1>
		<p>Learn with video tutorails</p>
	</div>
</div>
<div class="content">
		<div class="large-12 columns">
			<div class="large-4 columns medium-4 columns">
				<div class="title"><span>Blog</span></div>
				<p><span><%= image_tag "1.blog.gif",size: "60" %></span>You will get something new from me about Web Design and Web Developer, All you need just login you will see what u want to learn and what you want to build. Come on try with me....</p>
				<p><%= link_to "View all blog »",root_path, style: "color:#991a1e;text-decoration:underline;" %></p>
			</div>
			<div class="large-4 columns medium-4 columns">
				<div class="title"><span>The video Training</span></div>
				<p><span><%= image_tag "2.media.jpg",size: "60" %></span>Everything you learn with this tutorails from <%= link_to "Anakot.", root_path,style: "color:#3598DC;" %> I hope u guys can did it after watch this tutorails.  And if you got a problem can contact with <%= link_to " Email.", root_path,style: "color:#3598DC;" %></p>
				<p><%= link_to "View all tutorails »",root_path, style: "color:#991a1e;text-decoration:underline;" %></p>

			</div>
			<div class="large-4 columns medium-4 columns">
				<div class="title"><span>Why learn Rails.</span></div>
				<p><span><%= image_tag "3.studya.jpeg",size: "54", style: "margin-right:5px;" %></span>Rails was created in 2003 by <small style="font-size:1em;color:#3598DC;">David Heinemeier Hansson.</small>Rails is a web application framework running on the Ruby programming language.</p>
				
			</div>
		</div>	
		
		<div class="large-12 small-12 columns" style="margin-top: 30px;">
			<div class="large-6 small-12 columns">
				<div class="title1"><span>Latest Blog Tutorails</span></div>
				<%= render "site/box2" %>
			</div>
			<div class="large-6 small-12 columns">
				<div class="title1"><span>Latest Training</span></div>
				<%= render "site/train2" %>
			</div>
		</div>
		<div class="large-12 columns" style="margin-top:30px;">
		<div class="large-12 columns">
			<div class="title1"><span>Recently Course</span></div>
		</div>
		</div>
</div>

app/views/site/show.html.erb
<div class="sub-menu" style="height:80px;">
	<div class="content-sub">
		<h1><%= @product.name %></h1>
	</div>
</div>
<div class="mini-menu">
	<div class="content">
		<ul>
			<li><%= link_to "Tutorails",site_blog_path %></li>
			<li><%= link_to "View Course",root_path,style: "color:#888" %></li>
		</ul>
	</div>
</div>
<div class="content">
	<div class="large-12 small-12 columns">
		<div class="large-12 small-12 columns">
			<div class="box-show">
				<div class="show-vid"><%= @product.video.html_safe %></div>
				<div class="show-desc"><%= @product.description %></div>
			</div>

		<div id="disqus_thread" style="margin-top:50px;"></div>
		    <script type="text/javascript">
		        /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
		        var disqus_shortname = 'anakot'; // required: replace example with your forum shortname

		        /* * * DON'T EDIT BELOW THIS LINE * * */
		        (function() {
		            var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
		            dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
		            (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
		        })();
		    </script>
		    <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
		    <a href="http://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>
		</div>
		</div>
	</div>
</div>	

app/views/site/showtrain.html.erb
<div class="sub-menu" style="height:80px;">
	<div class="content-sub">
		<h1><%= @train.name %></h1>
	</div>
</div>
<div class="mini-menu">
	<div class="content">
		<ul>
			<li><%= link_to "Training Course",site_train_path %></li>
			<li><%= link_to "View Course",root_path,style: "color:#888" %></li>
		</ul>
	</div>
</div>
<div class="content">
	<div class="large-12 small-12 columns">
		<div class="large-12 small-12 columns">
			<div class="box-show">
				<div class="show-vid"><%= @train.video.html_safe %></div>
				<div class="show-desc"><%= @train.description %></div>
			</div>

		<div id="disqus_thread" style="margin-top:50px;"></div>
		    <script type="text/javascript">
		        /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
		        var disqus_shortname = 'anakot'; // required: replace example with your forum shortname

		        /* * * DON'T EDIT BELOW THIS LINE * * */
		        (function() {
		            var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
		            dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
		            (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
		        })();
		    </script>
		    <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
		    <a href="http://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>
		</div>
		</div>
	</div>
</div>	

app/views/site/train.html.erb
<div class="sub-menu">
	<div class="content-sub">
		<h1>All Training Course</h1>
		<p>Learn with my video you will did it....</p>
	</div>
</div>
<div class="mini-menu">
	<div class="content">
		<ul>
			<li><%= link_to "Training  Course",site_train_path,style: "color:#888" %></li>
		</ul>
	</div>
</div>
<div class="content-box">
<div class="title">
	<span>Latest Training</span>
</div>
<div class="last-tutorails">
	<% @tran.each do |tran| %>
		<div class="large-3 columns" style="padding-left: 0px;"><%= image_tag (tran.image),size: "300" %></div>
		<div class="large-9 columns" style="padding-left:0px;">
			<div class="pro-name"><%= tran.name %></div>	
			<div class="pro-desc"><%= tran.description %></div>
			<%= link_to "View last tutorails", site_showtrain_path(train_id: tran),class: "button tiny vine radius",style: "font-size:1em;margin-top:13px;" %>
		</div>	
	<% end %>
</div>
<div class="content"  style="margin-top:30px; padding:0px;">
<hr style="background:#f1f1f1;margin-bottom:23px;">
<% @trains.each do |t| %>
<%= link_to site_showtrain_path(train_id: t) do %>
	<div class="box">
		<div class="pro-img"><%= image_tag t.image,size: "200" %></div>
		<div class="pro-name"><%= t.name %></div>
		<div class="pro-des"><%= truncate(t.description,length: 130) %></div>
		<div class="footer-box">
			<p><i class="fa fa-clock-o"></i></p>
		</div>
	</div>
<% end %>
<% end %>
</div>

</div>
	

app/views/trains/_form.html.erb
<%= form_for(@train) do |f| %>
  <% if @train.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@train.errors.count, "error") %> prohibited this train from being saved:</h2>

      <ul>
      <% @train.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :logo %>
    <%= f.text_field :logo %>
  </div>
  <div class="field">
    <%= f.file_field :image %>
  </div>
  <div class="field">
    <%= f.label :video %>
    <%= f.text_field :video %>
  </div>
  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/trains/edit.html.erb
<h1>Editing train</h1>

<%= render 'form' %>

<%= link_to 'Show', @train %> |
<%= link_to 'Back', trains_path %>

app/views/trains/index.html.erb
<h1>Listing trains</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Image</th>
      <th>Video</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @trains.each do |train| %>
      <tr>
        <td><%= train.name %></td>
        <td><%= train.image %></td>
        <td><%= train.video %></td>
        <td><%= train.description %></td>
        <td><%= link_to 'Show', train %></td>
        <td><%= link_to 'Edit', edit_train_path(train) %></td>
        <td><%= link_to 'Destroy', train, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Train', new_train_path %>

app/views/trains/new.html.erb
<div class="content">
<h1>New train</h1>

<%= render 'form' %>

<%= link_to 'Back', trains_path %>
</div>

app/views/trains/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @train.name %>
</p>

<p>
  <strong>Image:</strong>
  <%= @train.image %>
</p>

<p>
  <strong>Video:</strong>
  <%= @train.video %>
</p>

<p>
  <strong>Description:</strong>
  <%= @train.description %>
</p>

<%= link_to 'Edit', edit_train_path(@train) %> |
<%= link_to 'Back', trains_path %>